; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat May 09 2020 00:01:35 GMT-0400 (Eastern Daylight Time)
M280 P3 S10 I1 ; deploy BLTouch

