; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat May 09 2020 00:01:37 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

